version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on: 
      - db
  app1:
    build: ./app1
    links:
      - db
    ports:
      - "5006:5006"
    depends_on: 
      - db
  app2:
    build: ./app2
    links:
      - db
    ports:
      - "5012:5012"
    depends_on: 
      - db

  db:
    image: mysql:8.0.25
    ports:
      - "30001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    
  db1:
    image: mysql:8.0.25
    ports:
      - "30002:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  db2:
    image: mysql:8.0.25
    ports:
      - "30003:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro